#!/usr/bin/env bash
set -ex
input=$1
tmp=$(mktemp --suffix .stl)
mkstl="./slicertemplate2stl $input $tmp"

$mkstl
fstl $tmp & pid=$!
trap "kill $pid" EXIT

while true ; do
  inotifywait $input
  $mkstl
done

